---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-storage
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  # TODO: Change to 'local'
  hostPath:
    path: "/some/path/to/use/inside"
